export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    lightGray: '#B3B4B6',
    accent: '#FFC231',
    accentRed: '#FB5D2E',
    accentPink: '#F96165',
  };
  
  export const Categories = [
    {
      name: 'Burger',
      image: require('./Images/burger.png'),
      items: [
        {
          name: 'Classic Burger',
          weight: 120,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('./Images/Burger/classicburger.png'),
          size: 'Large 8"',
          crust: 'Thick Crust',
          delivery: 25,
          ingredients: [
            require('./Images/flour.png'),
            require('./Images/cheese.png'),
            require('./Images/Sliced-Onion.png'),
            require('./Images/Tomato.png'),
          ],
        },
        {
          name: 'Aloo Tikki Burger',
          weight: 150,
          rating: '4.5',
          price: 99,
          isTopOfTheWeek: false,
          image: require('./Images/Burger/alootikkiburger.png'),
          size: 'Large 12"',
          crust: 'Thick Crust',
          delivery: 20,
          ingredients: [
            require('./Images/flour.png'),
            require('./Images/cheese.png'),
            require('./Images/Sliced-Onion.png'),
            require('./Images/Tomato.png'),
          ],
        },
        {
          name: 'Biggie Cheese',
          weight: 250,
          rating: '4.2',
          price: 299,
          isTopOfTheWeek: false,
          image: require('./Images/Burger/biggiecheese.png'),
          size: 'Large 10"',
          crust: 'Thick Crust',
          delivery: 35,
          ingredients: [
            require('./Images/flour.png'),
            require('./Images/cheese.png'),
            require('./Images/Sliced-Onion.png'),
            require('./Images/Tomato.png'),
          ],
        },
      ],
    },
    {
      name: 'Pizza',
      image: require('./Images/pizza.png'),
      items: [
        {
          name: 'Pepperoni Pizza',
          weight: 250,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('./Images/pizza/pepperonipizza.png'),
          size: 'Large 14"',
          crust: 'Thin Crust',
          delivery: 30,
          ingredients: [
            require('./Images/flour.png'),
            require('./Images/cheese.png'),
            require('./Images/Sliced-Onion.png'),
            require('./Images/Tomato.png'),
          ],
        },
        {
          name: 'Plain Cheese Pizza',
          weight: 300,
          rating: '4.5',
          price: 299,
          isTopOfTheWeek: false,
          image: require('./Images/pizza/plaincheesepizza.png'),
          size: 'Large 16"',
          crust: 'Thin Cheese',
          delivery: 25,
          ingredients: [
            require('./Images/flour.png'),
            require('./Images/cheese.png'),
            require('./Images/Sliced-Onion.png'),
            require('./Images/Tomato.png'),
          ],
        },
        {
          name: 'Mexican Green Wave',
          weight: 350,
          rating: '4.2',
          price: 499,
          isTopOfTheWeek: false,
          image: require('./Images/pizza/mexicangreenwave.png'),
          size: 'Large 15"',
          crust: 'Thin Crust',
          delivery: 45,
          ingredients: [
            require('./Images/flour.png'),
            require('./Images/cheese.png'),
            require('./Images/Sliced-Onion.png'),
            require('./Images/Tomato.png'),
          ],
        },
      ],
    },
    {
      name: 'Soft Drinks',
      image: require('./Images/softdrinks.png'),
      items: [
        {
          name: 'Coco Cola',
          weight: 200,
          rating: '5.0',
          price: 299,
          isTopOfTheWeek: true,
          image: require('./Images/softDrinks/cocacola.png'),
          size: 'Medium Glass',
          crust: 'Small Ice',
          delivery: 10,
          ingredients: [require('./Images/softDrinks/cocacola.png')],
        },
        {
          name: 'Orange Juice',
          weight: 500,
          rating: '4.5',
          price: 199,
          isTopOfTheWeek: false,
          image: require('./Images/softDrinks/orange.png'),
          size: 'LArge Glass',
          crust: 'Large Ice',
          delivery: 8,
          ingredients: [require('./Images/softDrinks/orange.png')],
        },
        {
          name: 'Mango Juice',
          weight: 150,
          rating: '4.2',
          price: 99,
          isTopOfTheWeek: false,
          image: require('./Images/softDrinks/mango.png'),
          size: 'Large Glass',
          crust: 'Small Ice',
          delivery: 5,
          ingredients: [require('./Images/softDrinks/mango.png')],
        },
      ],
    },
  ];